### ISSUE TITLE
API and Database

### ISSUE THREAD

**Issue by bowmanmc** [codefordayton/floswhistle#4]
We need a simple API for the application to submit reports to. We need some mechanism in place to keep spam bots from bringing down the system. We should also limit the number of times a specific user can submit a report. We were initially thinking once per 12 hours (to catch am/pm shifts).

We'd love to go cheap, but use something we can scale easily. AWS seems like a logical choice, but other options should be considered.

**Comment by DavidEBest** [comment]
In the interest of not overcomplicating things at the beginning, I'll configure nginx to prevent request flooding. Not a full DDOS solution, but should be more than adequate at the outset.

AWS will work.

**Comment by DavidEBest** [comment]
The once per 12 hours thing would require us to keep some sort of unique identifier. We can't (and don't want) to get a unique id from the device itself, but perhaps we could store a hash of the IP + User Agent? Certainly not guaranteed unique and it would be game-able (change WIFI network to report again), but it isn't super invasive and doesn't require a cookie. Thoughts?

**Comment by KaiserCode** [comment]
Have you thought about using captcha verification or a button that says I'm
not a robot w/ user verification.
